theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

title: WGCEP
description: Working Group on California Earthquake Probabilities
logo: resources/wgcep_logo_full.png
show_downloads: false
