theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

title: OpenSHA
description: Open-Source Seismic Hazard Analysis
logo: resources/opensha_logo.png
show_downloads: false
